DROP TABLE IF EXISTS products;


CREATE TABLE products (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    type VARCHAR(250) DEFAULT NULL,
    price DOUBLE DEFAULT NULL,
    store_address VARCHAR(250) DEFAULT NULL,
    color VARCHAR(250) DEFAULT NULL,
    gb_limit DOUBLE DEFAULT NULL,
    created_dt TIMESTAMP WITH TIME ZONE DEFAULT now(),
    modified_dt TIMESTAMP WITH TIME ZONE DEFAULT now()
);